version: 2
builds:
  - main: ./cmd/goxe
    env: [CGO_ENABLED=0]
    goos:
      - linux
      - windows
      - darwin
    goarch: 
      - amd64
      - arm64
    ldflags:
      - -X main.version=v{{.Version}}
      - -s -w

archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip


nfpms:
  - maintainer: Dylan Marcano (Nxus) <nxusdev@protonmail.com>
    description: Is a log reduction tool that normalizes, filters, and aggregates repeated messages to reduce noise and storage.
    homepage: https://github.com/DumbNoxx/Goxe
    license: Apache-2.0
    formats:
      - deb
      - rpm
      - apk 

