# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

tasks:
  dev:
    desc: Run the app in development mode
    cmds:
      - echo "Running the application"
      - go run ./cmd/goxe .
    silent: true
  build:
    desc: Building program in golang
    cmds:
      - echo "Built application in /bin"
      - go build -o bin/goxe ./cmd/goxe 
    silent: true 
  test:
    desc: Run testing application
    cmds:
      - echo "Running test"
      - go test -bench=. -benchmem ./cmd/goxe
    silent: true
